<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.550">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Carlos Esteban Aguilar Vargas">
<meta name="author" content="Augusto José Niño">

<title>Integración de datos meteorológicos de superficie y Sentinel-2 para la estimación exploratoria de Kc dinámico y ETc espacial en una cobertura de pasturas</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="proyecto_riegos_final_articulo_files/libs/clipboard/clipboard.min.js"></script>
<script src="proyecto_riegos_final_articulo_files/libs/quarto-html/quarto.js"></script>
<script src="proyecto_riegos_final_articulo_files/libs/quarto-html/popper.min.js"></script>
<script src="proyecto_riegos_final_articulo_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="proyecto_riegos_final_articulo_files/libs/quarto-html/anchor.min.js"></script>
<link href="proyecto_riegos_final_articulo_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="proyecto_riegos_final_articulo_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="proyecto_riegos_final_articulo_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="proyecto_riegos_final_articulo_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="proyecto_riegos_final_articulo_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#resumen" id="toc-resumen" class="nav-link active" data-scroll-target="#resumen"><span class="header-section-number">1</span> Resumen</a></li>
  <li><a href="#introducción" id="toc-introducción" class="nav-link" data-scroll-target="#introducción"><span class="header-section-number">2</span> Introducción</a></li>
  <li><a href="#objetivos" id="toc-objetivos" class="nav-link" data-scroll-target="#objetivos"><span class="header-section-number">3</span> Objetivos</a>
  <ul class="collapse">
  <li><a href="#objetivo-general" id="toc-objetivo-general" class="nav-link" data-scroll-target="#objetivo-general"><span class="header-section-number">3.1</span> Objetivo general</a></li>
  <li><a href="#objetivos-específicos" id="toc-objetivos-específicos" class="nav-link" data-scroll-target="#objetivos-específicos"><span class="header-section-number">3.2</span> Objetivos específicos</a></li>
  </ul></li>
  <li><a href="#área-de-estudio" id="toc-área-de-estudio" class="nav-link" data-scroll-target="#área-de-estudio"><span class="header-section-number">4</span> Área de estudio</a></li>
  <li><a href="#datos-y-metodología" id="toc-datos-y-metodología" class="nav-link" data-scroll-target="#datos-y-metodología"><span class="header-section-number">5</span> Datos y metodología</a>
  <ul class="collapse">
  <li><a href="#datos-meteorológicos" id="toc-datos-meteorológicos" class="nav-link" data-scroll-target="#datos-meteorológicos"><span class="header-section-number">5.1</span> Datos meteorológicos</a></li>
  <li><a href="#procesamiento-sentinel-2" id="toc-procesamiento-sentinel-2" class="nav-link" data-scroll-target="#procesamiento-sentinel-2"><span class="header-section-number">5.2</span> Procesamiento Sentinel-2</a></li>
  <li><a href="#construcción-del-kc-dinámico" id="toc-construcción-del-kc-dinámico" class="nav-link" data-scroll-target="#construcción-del-kc-dinámico"><span class="header-section-number">5.3</span> Construcción del Kc dinámico</a></li>
  <li><a href="#enmascaramiento-espacial-y-aoi-limpio" id="toc-enmascaramiento-espacial-y-aoi-limpio" class="nav-link" data-scroll-target="#enmascaramiento-espacial-y-aoi-limpio"><span class="header-section-number">5.4</span> Enmascaramiento espacial y AOI limpio</a></li>
  <li><a href="#diagnóstico-landsatlst" id="toc-diagnóstico-landsatlst" class="nav-link" data-scroll-target="#diagnóstico-landsatlst"><span class="header-section-number">5.5</span> Diagnóstico Landsat/LST</a></li>
  </ul></li>
  <li><a href="#resultados" id="toc-resultados" class="nav-link" data-scroll-target="#resultados"><span class="header-section-number">6</span> Resultados</a>
  <ul class="collapse">
  <li><a href="#relación-entre-et-de-estación-y-proxies-sentinel-2" id="toc-relación-entre-et-de-estación-y-proxies-sentinel-2" class="nav-link" data-scroll-target="#relación-entre-et-de-estación-y-proxies-sentinel-2"><span class="header-section-number">6.1</span> Relación entre ET de estación y proxies Sentinel-2</a></li>
  <li><a href="#kc-dinámico-y-etc-espacial-en-buffer-inicial" id="toc-kc-dinámico-y-etc-espacial-en-buffer-inicial" class="nav-link" data-scroll-target="#kc-dinámico-y-etc-espacial-en-buffer-inicial"><span class="header-section-number">6.2</span> Kc dinámico y ETc espacial en buffer inicial</a></li>
  <li><a href="#kc-dinámico-y-etc-espacial-en-aoi-limpio-de-pasturas" id="toc-kc-dinámico-y-etc-espacial-en-aoi-limpio-de-pasturas" class="nav-link" data-scroll-target="#kc-dinámico-y-etc-espacial-en-aoi-limpio-de-pasturas"><span class="header-section-number">6.3</span> Kc dinámico y ETc espacial en AOI limpio de pasturas</a></li>
  <li><a href="#comparación-temporal-de-et-base-kc-y-etc" id="toc-comparación-temporal-de-et-base-kc-y-etc" class="nav-link" data-scroll-target="#comparación-temporal-de-et-base-kc-y-etc"><span class="header-section-number">6.4</span> Comparación temporal de ET base, Kc y ETc</a></li>
  <li><a href="#diagnóstico-landsatlst-1" id="toc-diagnóstico-landsatlst-1" class="nav-link" data-scroll-target="#diagnóstico-landsatlst-1"><span class="header-section-number">6.5</span> Diagnóstico Landsat/LST</a></li>
  </ul></li>
  <li><a href="#discusión" id="toc-discusión" class="nav-link" data-scroll-target="#discusión"><span class="header-section-number">7</span> Discusión</a>
  <ul class="collapse">
  <li><a href="#viabilidad-del-método" id="toc-viabilidad-del-método" class="nav-link" data-scroll-target="#viabilidad-del-método"><span class="header-section-number">7.1</span> Viabilidad del método</a></li>
  <li><a href="#importancia-del-aoi-limpio" id="toc-importancia-del-aoi-limpio" class="nav-link" data-scroll-target="#importancia-del-aoi-limpio"><span class="header-section-number">7.2</span> Importancia del AOI limpio</a></li>
  <li><a href="#limitaciones-por-disponibilidad-de-datos" id="toc-limitaciones-por-disponibilidad-de-datos" class="nav-link" data-scroll-target="#limitaciones-por-disponibilidad-de-datos"><span class="header-section-number">7.3</span> Limitaciones por disponibilidad de datos</a></li>
  <li><a href="#alcance-de-la-etc-espacial" id="toc-alcance-de-la-etc-espacial" class="nav-link" data-scroll-target="#alcance-de-la-etc-espacial"><span class="header-section-number">7.4</span> Alcance de la ETc espacial</a></li>
  </ul></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones"><span class="header-section-number">8</span> Conclusiones</a></li>
  <li><a href="#recomendaciones" id="toc-recomendaciones" class="nav-link" data-scroll-target="#recomendaciones"><span class="header-section-number">9</span> Recomendaciones</a>
  <ul class="collapse">
  <li><a href="#disponibilidad-de-datos-código-y-reproducibilidad" id="toc-disponibilidad-de-datos-código-y-reproducibilidad" class="nav-link" data-scroll-target="#disponibilidad-de-datos-código-y-reproducibilidad"><span class="header-section-number">9.1</span> Disponibilidad de datos, código y reproducibilidad</a></li>
  </ul></li>
  <li><a href="#referencias" id="toc-referencias" class="nav-link" data-scroll-target="#referencias"><span class="header-section-number">10</span> Referencias</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Otros formatos</h2><ul><li><a href="proyecto_riegos_final_articulo.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Integración de datos meteorológicos de superficie y Sentinel-2 para la estimación exploratoria de Kc dinámico y ETc espacial en una cobertura de pasturas</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autores/as</div>
    <div class="quarto-title-meta-contents">
             <p>Carlos Esteban Aguilar Vargas </p>
             <p>Augusto José Niño </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="resumen" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Resumen</h1>
<p>Este trabajo evaluó la integración entre datos meteorológicos de superficie y productos derivados de sensores remotos para construir una aproximación exploratoria de coeficiente de cultivo dinámico (Kc) y evapotranspiración del cultivo espacializada (ETc) en una cobertura de pasturas alrededor de una estación meteorológica. La serie meteorológica fue depurada y corregida temporalmente, obteniendo 158 días diarios entre el 30 de julio de 2025 y el 13 de enero de 2026, de los cuales 143 fueron considerados válidos para análisis. A partir de Sentinel-2 se evaluaron índices espectrales como NDVI, EVI, SAVI y NDRE, y se encontró que SAVI presentó la asociación más fuerte con la ET diaria de estación en el mismo día (n = 8; r = 0.900; R² = 0.810; RMSE = 0.173 mm día<sup>-1</sup>). Posteriormente, se construyó un Kc dinámico exploratorio basado principalmente en SAVI, escalado entre 0.70 y 1.05, y se generó una ETc espacial como el producto entre la ET base de estación y el Kc dinámico. El análisis espacial fue refinado mediante un AOI limpio de pasturas y la exclusión de construcciones y superficies duras, lo cual permitió reducir interferencias espectrales. La rama Landsat/LST se conservó como diagnóstico térmico complementario debido a la baja disponibilidad de escenas válidas (n = 4). Los resultados muestran que el método es viable como aproximación exploratoria y reproducible, aunque su robustez depende de una mayor continuidad de datos meteorológicos y de una mayor disponibilidad de imágenes satelitales válidas.</p>
<p><strong>Palabras clave:</strong> evapotranspiración, Kc dinámico, Sentinel-2, SAVI, pasturas, estación meteorológica, riego, ETc espacial.</p>
</section>
<section id="introducción" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Introducción</h1>
<p>La evapotranspiración es una variable central en la planificación del riego, el balance hídrico agrícola y la interpretación de la demanda de agua de los cultivos. En condiciones operativas, la ET suele estimarse mediante estaciones meteorológicas, modelos de referencia o aproximaciones basadas en variables climáticas. Sin embargo, estas mediciones representan una señal puntual o local, mientras que la variabilidad espacial de la cobertura vegetal puede modificar la demanda hídrica dentro del área de influencia de la estación.</p>
<p>La percepción remota ofrece una alternativa para incorporar información espacial sobre el estado de la vegetación. Índices como NDVI, SAVI, EVI y NDRE permiten aproximar variaciones en vigor, cobertura y respuesta espectral de la superficie. No obstante, estos índices no calculan evapotranspiración por sí mismos; su valor metodológico está en que pueden funcionar como proxies de estado de la cobertura o como insumo para construir coeficientes dinámicos que modulen una ET estimada desde superficie.</p>
<p>En este proyecto se propuso una ruta metodológica para pasar de una señal puntual de estación meteorológica a una representación espacial exploratoria de Kc dinámico y ETc. El enfoque combina tres elementos: una serie meteorológica depurada, imágenes Sentinel-2 válidas y una delimitación espacial refinada del área de pasturas. Adicionalmente, se exploró una rama térmica con Landsat/LST, pero esta se mantuvo como diagnóstico debido a la baja disponibilidad de observaciones válidas.</p>
</section>
<section id="objetivos" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Objetivos</h1>
<section id="objetivo-general" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="objetivo-general"><span class="header-section-number">3.1</span> Objetivo general</h2>
<p>Evaluar la integración entre datos meteorológicos de superficie y productos derivados de Sentinel-2 para construir una aproximación exploratoria de Kc dinámico y ETc espacial en una cobertura de pasturas alrededor de una estación meteorológica.</p>
</section>
<section id="objetivos-específicos" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="objetivos-específicos"><span class="header-section-number">3.2</span> Objetivos específicos</h2>
<ol type="1">
<li>Depurar y estructurar la serie meteorológica diaria de la estación, garantizando coherencia temporal y criterios mínimos de calidad.</li>
<li>Evaluar la relación entre la ET diaria de estación y proxies espectrales derivados de Sentinel-2.</li>
<li>Construir un Kc dinámico exploratorio a partir de índices espectrales, usando SAVI como índice principal y NDVI como comparación.</li>
<li>Generar mapas de ETc espacial como producto entre la ET base de estación y el Kc dinámico.</li>
<li>Refinar la unidad espacial de análisis mediante un AOI limpio de pasturas y la exclusión de construcciones o superficies duras.</li>
<li>Diagnosticar la viabilidad de una rama térmica Landsat/LST como complemento metodológico.</li>
</ol>
</section>
</section>
<section id="área-de-estudio" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Área de estudio</h1>
<p>El estudio se desarrolló en el entorno de una estación meteorológica ubicada en la Universidad Nacional de Colombia, sede Bogotá. La unidad espacial inicial fue un buffer de 300 m alrededor de la estación. Posteriormente, este entorno fue refinado mediante la delimitación de un AOI de pasturas y la exclusión de construcciones, techos, vías y superficies duras que podían generar interferencia espectral.</p>
<div id="fig-localizacion" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-localizacion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="data/article_figures/maps_qgis/exports_png/fig_map01_localizacion_area_estudio.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-localizacion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;1: Localización del área de estudio, estación meteorológica, buffer inicial de 300 m y AOI final de pasturas. Esta unidad espacial permitió relacionar la señal puntual de estación con variables espectrales derivadas de Sentinel-2.
</figcaption>
</figure>
</div>
<p>El refinamiento espacial fue una decisión metodológica central. El análisis inicial sobre el buffer completo incluía zonas construidas y superficies no vegetadas. Al excluir estas áreas, las estadísticas de Kc y ETc se hicieron más representativas de la cobertura de pasturas, que era la cobertura de interés para la relación estación–satélite.</p>
<div id="fig-aoi" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-aoi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="data/article_figures/maps_qgis/exports_png/fig_map02_aoi_limpio_exclusiones.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-aoi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;2: Refinamiento espacial del área de análisis mediante exclusión de construcciones y superficies no vegetadas. Este procedimiento redujo la mezcla espectral y permitió calcular estadísticas de Kc/ETc sobre una cobertura más representativa de pasturas.
</figcaption>
</figure>
</div>
</section>
<section id="datos-y-metodología" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Datos y metodología</h1>
<section id="datos-meteorológicos" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="datos-meteorológicos"><span class="header-section-number">5.1</span> Datos meteorológicos</h2>
<p>La estación meteorológica registró información con resolución nominal de 5 minutos. Durante la depuración se corrigió un problema crítico de interpretación de fechas, en el cual fechas en formato ISO podían ser leídas con inversión de mes y día. Tras la corrección, la serie diaria quedó comprendida entre el 30 de julio de 2025 y el 13 de enero de 2026.</p>
<p>La variable de referencia fue la ET diaria exterior reportada por la estación. Esta ET se interpretó como una referencia operativa modelada por el sistema de estación, no como una medición directa de ET real. Se usaron criterios de calidad diaria para conservar únicamente días con cobertura suficiente de registros y variables meteorológicas consistentes.</p>
<p><strong>Resumen de estación meteorológica:</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Indicador</th>
<th style="text-align: right;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rango temporal</td>
<td style="text-align: right;">2025-07-30 a 2026-01-13</td>
</tr>
<tr class="even">
<td>Días diarios disponibles</td>
<td style="text-align: right;">158</td>
</tr>
<tr class="odd">
<td>Días válidos para análisis</td>
<td style="text-align: right;">143</td>
</tr>
<tr class="even">
<td>ET media exterior</td>
<td style="text-align: right;">1.925 mm día<sup>-1</sup></td>
</tr>
<tr class="odd">
<td>Temperatura exterior media</td>
<td style="text-align: right;">14.988 °C</td>
</tr>
<tr class="even">
<td>Radiación exterior media</td>
<td style="text-align: right;">117.073</td>
</tr>
</tbody>
</table>
</section>
<section id="procesamiento-sentinel-2" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="procesamiento-sentinel-2"><span class="header-section-number">5.2</span> Procesamiento Sentinel-2</h2>
<p>Se extrajeron imágenes Sentinel-2 sobre el área de estudio y se calcularon índices espectrales: NDVI, EVI, SAVI y NDRE. Posteriormente, se cruzaron las fechas satelitales válidas con días meteorológicos válidos de estación. El cruce final Sentinel–estación produjo 8 observaciones analysis-ready entre el 20 de agosto y el 28 de diciembre de 2025.</p>
<p>La relación entre la ET diaria de estación y los índices espectrales se evaluó mediante regresiones lineales simples y correlaciones de Pearson y Spearman. Dado el tamaño muestral reducido, los resultados se interpretaron como exploratorios y se complementaron con análisis de robustez: leave-one-out, bootstrap y prueba de permutación.</p>
<div id="fig-timeline" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-timeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="data/article_figures/fig01_station_satellite_timeline.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-timeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3: Serie temporal de ET diaria de estación y fechas Sentinel-2 válidas utilizadas en el cruce estación–satélite.
</figcaption>
</figure>
</div>
</section>
<section id="construcción-del-kc-dinámico" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="construcción-del-kc-dinámico"><span class="header-section-number">5.3</span> Construcción del Kc dinámico</h2>
<p>El Kc dinámico se construyó como un coeficiente exploratorio relativo, escalado dentro del rango observado de cada índice en las fechas Sentinel-2 válidas. Se usó SAVI como índice principal debido a su mejor desempeño en la relación con ET diaria de estación. NDVI se conservó como comparación metodológica.</p>
<p>La formulación general fue:</p>
<p><span class="math display">\[
Kc_{dinámico} = Kc_{min} + \left( \frac{VI - VI_{min}}{VI_{max} - VI_{min}} \right)(Kc_{max} - Kc_{min})
\]</span></p>
<p>Donde <span class="math inline">\(VI\)</span> corresponde al índice espectral seleccionado. Para este proyecto se asumieron los siguientes límites exploratorios:</p>
<p><span class="math display">\[
Kc_{min} = 0.70
\]</span></p>
<p><span class="math display">\[
Kc_{max} = 1.05
\]</span></p>
<p>La ETc espacial se calculó como:</p>
<p><span class="math display">\[
ETc_{SAVI} = ET_{base\ estación} \times Kc_{SAVI\ dinámico}
\]</span></p>
<p>Este producto no corresponde a una medición directa de ET real ni a una estimación satelital física independiente. Su aporte principal es espacializar la ET de estación en función del vigor o cobertura vegetal observada por Sentinel-2.</p>
</section>
<section id="enmascaramiento-espacial-y-aoi-limpio" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="enmascaramiento-espacial-y-aoi-limpio"><span class="header-section-number">5.4</span> Enmascaramiento espacial y AOI limpio</h2>
<p>Los rasters de Kc/ETc fueron exportados desde Google Earth Engine y posteriormente enmascarados en QGIS/Python usando un AOI limpio de pasturas. Se excluyeron construcciones y superficies duras digitalizadas manualmente. Esta etapa permitió reducir la mezcla espectral dentro del buffer original y mejorar la representatividad agronómica del Kc.</p>
</section>
<section id="diagnóstico-landsatlst" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="diagnóstico-landsatlst"><span class="header-section-number">5.5</span> Diagnóstico Landsat/LST</h2>
<p>Además de Sentinel-2, se procesó una rama térmica con Landsat 8/9 LST. Esta variable se consideró conceptualmente relevante por su cercanía al balance energético superficial. Sin embargo, la disponibilidad de escenas válidas fue baja debido a nubosidad, sombras y enmascaramiento QA. Por esta razón, Landsat/LST se conservó como diagnóstico térmico complementario y no se utilizó para ajustar regresiones robustas.</p>
</section>
</section>
<section id="resultados" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Resultados</h1>
<section id="relación-entre-et-de-estación-y-proxies-sentinel-2" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="relación-entre-et-de-estación-y-proxies-sentinel-2"><span class="header-section-number">6.1</span> Relación entre ET de estación y proxies Sentinel-2</h2>
<p>El mejor modelo para ET diaria del mismo día fue el modelo con SAVI como predictor:</p>
<p><span class="math display">\[
ET = 0.773 + 5.137 \times SAVI
\]</span></p>
<p><strong>Desempeño del modelo principal:</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Métrica</th>
<th style="text-align: right;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>n</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td>Pearson r</td>
<td style="text-align: right;">0.900</td>
</tr>
<tr class="odd">
<td>Spearman rho</td>
<td style="text-align: right;">0.833</td>
</tr>
<tr class="even">
<td>R²</td>
<td style="text-align: right;">0.810</td>
</tr>
<tr class="odd">
<td>RMSE</td>
<td style="text-align: right;">0.173 mm día<sup>-1</sup></td>
</tr>
<tr class="even">
<td>MAE</td>
<td style="text-align: right;">0.146 mm día<sup>-1</sup></td>
</tr>
<tr class="odd">
<td>Pendiente</td>
<td style="text-align: right;">5.137</td>
</tr>
<tr class="even">
<td>Intercepto</td>
<td style="text-align: right;">0.773</td>
</tr>
</tbody>
</table>
<div id="fig-savi" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-savi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="data/article_figures/fig02_scatter_best_same_day_model.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-savi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4: Relación entre ET diaria de estación y SAVI del mismo día. El modelo presentó la mayor asociación entre los índices evaluados.
</figcaption>
</figure>
</div>
<p>El ranking de predictores para ET diaria del mismo día mostró que SAVI fue el índice de mejor desempeño, seguido de NDVI, NDRE y EVI.</p>
<table class="table">
<thead>
<tr class="header">
<th>Predictor</th>
<th style="text-align: right;">r</th>
<th style="text-align: right;">R²</th>
<th style="text-align: right;">RMSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SAVI</td>
<td style="text-align: right;">0.900</td>
<td style="text-align: right;">0.810</td>
<td style="text-align: right;">0.173</td>
</tr>
<tr class="even">
<td>NDVI</td>
<td style="text-align: right;">0.870</td>
<td style="text-align: right;">0.757</td>
<td style="text-align: right;">0.196</td>
</tr>
<tr class="odd">
<td>NDRE</td>
<td style="text-align: right;">0.843</td>
<td style="text-align: right;">0.710</td>
<td style="text-align: right;">0.214</td>
</tr>
<tr class="even">
<td>EVI</td>
<td style="text-align: right;">0.811</td>
<td style="text-align: right;">0.657</td>
<td style="text-align: right;">0.233</td>
</tr>
</tbody>
</table>
<div id="fig-predictores" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-predictores-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="data/article_figures/fig03_scatter_same_day_predictor_grid.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-predictores-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5: Comparación de predictores espectrales para ET del mismo día.
</figcaption>
</figure>
</div>
<p>Los análisis de robustez mostraron que la señal principal no dependió de una única observación. En leave-one-out, R² varió entre 0.722 y 0.866, mientras que la prueba de permutación presentó un valor p empírico bilateral de 0.005699. Estos resultados respaldan la existencia de una asociación exploratoria entre SAVI y la ET diaria de estación, aunque el tamaño muestral sigue siendo reducido.</p>
</section>
<section id="kc-dinámico-y-etc-espacial-en-buffer-inicial" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="kc-dinámico-y-etc-espacial-en-buffer-inicial"><span class="header-section-number">6.2</span> Kc dinámico y ETc espacial en buffer inicial</h2>
<p>Antes del enmascaramiento por AOI limpio, el Kc dinámico basado en SAVI presentó un valor medio de 0.862, con un rango temporal entre 0.783 y 0.935. La ETc basada en SAVI tuvo una media de 2.100 mm día<sup>-1</sup>, con valores entre 1.409 y 2.702 mm día<sup>-1</sup>. En promedio, la ETc SAVI representó el 86.19 % de la ET base de estación.</p>
<p>Estos valores fueron útiles como primera aproximación, pero el buffer original contenía construcciones y superficies no vegetadas. Por esta razón, el resultado final se reporta principalmente sobre el AOI limpio de pasturas.</p>
</section>
<section id="kc-dinámico-y-etc-espacial-en-aoi-limpio-de-pasturas" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="kc-dinámico-y-etc-espacial-en-aoi-limpio-de-pasturas"><span class="header-section-number">6.3</span> Kc dinámico y ETc espacial en AOI limpio de pasturas</h2>
<p>Tras excluir construcciones y superficies duras, el Kc dinámico basado en SAVI aumentó en varias fechas, lo que confirma que el buffer inicial mezclaba coberturas no vegetadas con la cobertura de pasturas. La siguiente tabla resume las fechas seleccionadas para la composición multitemporal.</p>
<table class="table">
<colgroup>
<col style="width: 21%">
<col style="width: 28%">
<col style="width: 28%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Fecha</th>
<th style="text-align: right;">Kc SAVI limpio</th>
<th style="text-align: right;">ETc SAVI limpia (mm día<sup>-1</sup>)</th>
<th>Interpretación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2025-09-11</td>
<td style="text-align: right;">0.986</td>
<td style="text-align: right;">2.851</td>
<td>Mayor vigor/cobertura relativa y ETc alta</td>
</tr>
<tr class="even">
<td>2025-11-18</td>
<td style="text-align: right;">0.857</td>
<td style="text-align: right;">1.722</td>
<td>Descenso intermedio de Kc y ETc</td>
</tr>
<tr class="odd">
<td>2025-12-18</td>
<td style="text-align: right;">0.819</td>
<td style="text-align: right;">1.475</td>
<td>Menor Kc y menor ETc de la serie seleccionada</td>
</tr>
<tr class="even">
<td>2025-12-28</td>
<td style="text-align: right;">0.969</td>
<td style="text-align: right;">2.742</td>
<td>Recuperación del Kc y ETc alta</td>
</tr>
</tbody>
</table>
<p>La composición multitemporal del Kc muestra cambios espaciales y temporales en el vigor/cobertura vegetal del AOI limpio. La escala fue mantenida constante entre paneles para permitir comparación directa.</p>
<div id="fig-kc-multi" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-kc-multi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="data/article_figures/maps_qgis/exports_png/fig_map03_kc_savi_multitemporal.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-kc-multi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6: Variación multitemporal del Kc dinámico basado en SAVI en cuatro fechas Sentinel-2 seleccionadas. La escala de color se mantuvo constante entre paneles para permitir la comparación temporal. El cálculo se realizó sobre el AOI limpio de pasturas, excluyendo construcciones y superficies duras.
</figcaption>
</figure>
</div>
<p>La composición de ETc espacial muestra la lámina diaria resultante de multiplicar la ET base de estación por el Kc dinámico SAVI. Los cambios entre fechas reflejan tanto la variabilidad meteorológica de la ET de estación como la modulación espacial asociada al estado de la cobertura vegetal.</p>
<div id="fig-etc-multi" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-etc-multi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="data/article_figures/maps_qgis/exports_png/fig_map04_etc_savi_multitemporal.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-etc-multi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7: ETc espacial basada en Kc dinámico SAVI para cuatro fechas Sentinel-2 representativas. Los valores están expresados en mm día<sup>-1</sup>. La ETc no corresponde a una medición directa, sino a una espacialización exploratoria de la ET de estación modulada por la respuesta espectral de la cobertura vegetal.
</figcaption>
</figure>
</div>
</section>
<section id="comparación-temporal-de-et-base-kc-y-etc" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="comparación-temporal-de-et-base-kc-y-etc"><span class="header-section-number">6.4</span> Comparación temporal de ET base, Kc y ETc</h2>
<p>La ETc dinámica mantiene una alta relación con la ET base, lo cual es esperable por construcción matemática, ya que ETc se calculó como el producto entre ET base y Kc. Por esta razón, la interpretación principal no debe centrarse en la correlación ET base–ETc, sino en la capacidad del Kc de introducir variabilidad espacial y temporal asociada al estado de la cobertura.</p>
<div id="fig-etc-serie" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-etc-serie-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="data/article_figures/fig08_dynamic_etc_timeseries.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-etc-serie-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;8: Serie temporal de ET base de estación y ETc dinámica basada en SAVI y NDVI.
</figcaption>
</figure>
</div>
<div id="fig-kc-serie" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-kc-serie-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="data/article_figures/fig09_dynamic_kc_timeseries.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-kc-serie-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;9: Evolución temporal del Kc dinámico basado en SAVI y NDVI.
</figcaption>
</figure>
</div>
</section>
<section id="diagnóstico-landsatlst-1" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="diagnóstico-landsatlst-1"><span class="header-section-number">6.5</span> Diagnóstico Landsat/LST</h2>
<p>La rama Landsat/LST produjo 18 escenas sobre el ROI, de las cuales solo 4 fueron válidas después del enmascaramiento de calidad. Las cuatro fechas analysis-ready se ubicaron entre el 7 de noviembre y el 17 de diciembre de 2025. La mediana del porcentaje de píxeles válidos fue 0 %, lo que evidencia una limitación fuerte por nubosidad, sombras o enmascaramiento QA.</p>
<table class="table">
<thead>
<tr class="header">
<th>Indicador</th>
<th style="text-align: right;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Escenas Landsat ROI</td>
<td style="text-align: right;">18</td>
</tr>
<tr class="even">
<td>Escenas válidas</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td>Fechas analysis-ready</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td>Rango analysis-ready</td>
<td style="text-align: right;">2025-11-07 a 2025-12-17</td>
</tr>
<tr class="odd">
<td>LST media en fechas válidas</td>
<td style="text-align: right;">29.125 °C</td>
</tr>
<tr class="even">
<td>Temperatura media exterior</td>
<td style="text-align: right;">15.287 °C</td>
</tr>
<tr class="odd">
<td>Diferencia LST - T aire</td>
<td style="text-align: right;">13.837 °C</td>
</tr>
</tbody>
</table>
<p>Dado el número reducido de coincidencias válidas, Landsat/LST no se usó para inferencia estadística. Su aporte fue diagnóstico y metodológico.</p>
<div id="fig-landsat-valid" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-landsat-valid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="data/article_figures/fig06_landsat_valid_pixel_pct.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-landsat-valid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;10: Disponibilidad de píxeles válidos Landsat/LST sobre el ROI.
</figcaption>
</figure>
</div>
<div id="fig-landsat-tair" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-landsat-tair-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="data/article_figures/fig07_landsat_lst_vs_tair.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-landsat-tair-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11: Comparación descriptiva entre LST Landsat y temperatura media exterior de la estación.
</figcaption>
</figure>
</div>
</section>
</section>
<section id="discusión" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Discusión</h1>
<section id="viabilidad-del-método" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="viabilidad-del-método"><span class="header-section-number">7.1</span> Viabilidad del método</h2>
<p>Los resultados muestran que el método es viable para construir una aproximación espacial de Kc dinámico y ETc a partir de la integración entre estación meteorológica y Sentinel-2. El flujo permitió pasar de una señal puntual de ET de estación a superficies espaciales de Kc y ETc, usando índices espectrales como moduladores del estado de la cobertura vegetal.</p>
<p>El resultado más consistente fue la relación entre ET diaria y SAVI. Esto justificó usar SAVI como índice principal para el Kc dinámico. No obstante, NDVI presentó resultados similares y se mantuvo como comparación metodológica. La alta consistencia entre Kc SAVI y Kc NDVI sugiere que ambos índices capturan patrones similares de cobertura, aunque SAVI tuvo mejor desempeño empírico frente a la ET diaria de estación.</p>
</section>
<section id="importancia-del-aoi-limpio" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="importancia-del-aoi-limpio"><span class="header-section-number">7.2</span> Importancia del AOI limpio</h2>
<p>La comparación entre el buffer inicial y el AOI limpio evidenció que la delimitación espacial es una decisión crítica. En un entorno urbano-universitario, un buffer circular puede incluir techos, vías, invernaderos y superficies duras. Estas coberturas no representan la superficie agrícola de interés y pueden alterar las estadísticas espectrales. La exclusión de construcciones permitió obtener un Kc más coherente con la cobertura de pasturas.</p>
</section>
<section id="limitaciones-por-disponibilidad-de-datos" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="limitaciones-por-disponibilidad-de-datos"><span class="header-section-number">7.3</span> Limitaciones por disponibilidad de datos</h2>
<p>La principal limitación del estudio fue el tamaño muestral. Aunque la estación tuvo 143 días válidos, el número de fechas analysis-ready se redujo al exigir coincidencia con imágenes Sentinel-2 válidas y días meteorológicos completos. Además, las imágenes satelitales fueron afectadas por nubosidad, sombras, enmascaramiento de píxeles y disponibilidad temporal.</p>
<p>El método depende críticamente de dos condiciones: la disponibilidad de imágenes satelitales válidas y la calidad/continuidad de las mediciones de la estación meteorológica. Durante el procesamiento se excluyeron numerosas observaciones por falta de coincidencia temporal, baja calidad satelital o días meteorológicos no válidos. Por tanto, se recomienda ampliar la serie temporal de la estación, fortalecer el control de calidad de los sensores y mantener un registro continuo que permita incrementar el número de fechas analysis-ready.</p>
</section>
<section id="alcance-de-la-etc-espacial" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="alcance-de-la-etc-espacial"><span class="header-section-number">7.4</span> Alcance de la ETc espacial</h2>
<p>La ETc espacial generada en este trabajo no debe interpretarse como una medición directa de ET real ni como una estimación satelital física independiente. Es una espacialización exploratoria de la ET de estación modulada por un Kc dinámico basado en el estado espectral de la cobertura vegetal. Su utilidad está en representar heterogeneidad espacial relativa y ofrecer una ruta metodológica reproducible para apoyar decisiones de riego.</p>
</section>
</section>
<section id="conclusiones" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Conclusiones</h1>
<ol type="1">
<li><p>La depuración temporal de la estación meteorológica fue fundamental para garantizar la coherencia del análisis. Después de corregir el parseo de fechas, la serie diaria quedó entre el 30 de julio de 2025 y el 13 de enero de 2026, con 143 días válidos.</p></li>
<li><p>Sentinel-2 permitió construir una relación exploratoria entre ET diaria de estación y proxies espectrales. SAVI fue el predictor con mejor desempeño para ET diaria del mismo día, con r = 0.900 y R² = 0.810.</p></li>
<li><p>Se construyó un Kc dinámico exploratorio basado en SAVI, escalado entre 0.70 y 1.05. Este Kc permitió espacializar la ET de estación y generar mapas de ETc en mm día<sup>-1</sup>.</p></li>
<li><p>La delimitación del AOI limpio de pasturas y la exclusión de construcciones mejoraron la representatividad espacial del Kc dinámico. Este paso fue clave para reducir mezcla espectral y enfocar el análisis en la cobertura vegetal de interés.</p></li>
<li><p>La rama Landsat/LST fue metodológicamente relevante, pero la disponibilidad efectiva de observaciones fue insuficiente para ajustar regresiones robustas. Por tanto, se mantuvo como diagnóstico térmico complementario.</p></li>
<li><p>La metodología es viable y reproducible, pero requiere una serie temporal meteorológica más amplia y una mayor disponibilidad de imágenes satelitales válidas para pasar de una aproximación exploratoria a una validación robusta.</p></li>
</ol>
</section>
<section id="recomendaciones" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Recomendaciones</h1>
<ul>
<li>Ampliar la serie temporal de la estación meteorológica para cubrir más ciclos climáticos y aumentar el número de coincidencias con Sentinel-2.</li>
<li>Fortalecer el control de calidad de sensores y registros meteorológicos, especialmente en variables asociadas a ET.</li>
<li>Mantener el uso de AOI limpios de cobertura vegetal y evitar promedios sobre buffers que incluyan construcciones o superficies duras.</li>
<li>Evaluar el método en otras coberturas o cultivos para explorar la transferencia de la metodología.</li>
<li>Incorporar mediciones independientes de ET real, como lisímetro o balance hídrico controlado, para validar el Kc dinámico y la ETc espacial.</li>
</ul>
<section id="disponibilidad-de-datos-código-y-reproducibilidad" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="disponibilidad-de-datos-código-y-reproducibilidad"><span class="header-section-number">9.1</span> Disponibilidad de datos, código y reproducibilidad</h2>
<p>Con el fin de favorecer la transparencia metodológica, la trazabilidad del procesamiento y la reproducibilidad de los resultados, los scripts, insumos procesados, tablas, figuras y documentación técnica del proyecto se encuentran disponibles en un repositorio público de GitHub:</p>
<p><a href="https://github.com/ceaguilarv/Proyecto-Riegos-Y-Drenajes">Repositorio público del proyecto en GitHub</a></p>
<p>El repositorio contiene el flujo de trabajo implementado en Python y Google Earth Engine para la depuración de la estación meteorológica, el procesamiento de Sentinel-2, el diagnóstico térmico Landsat/LST, la construcción del Kc dinámico, la generación de ETc espacial exploratoria y la elaboración de tablas y figuras finales. Los productos se comparten bajo un enfoque de ciencia abierta, reconociendo que la interpretación de los resultados depende de los supuestos metodológicos documentados, la calidad de los datos meteorológicos disponibles y la disponibilidad efectiva de imágenes satelitales válidas.</p>
</section>
</section>
<section id="referencias" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Referencias</h1>
<p>Allen, R. G., Pereira, L. S., Raes, D., &amp; Smith, M. (1998). <em>Crop evapotranspiration: Guidelines for computing crop water requirements</em>. FAO Irrigation and Drainage Paper 56.</p>
<p>Bastiaanssen, W. G. M., Menenti, M., Feddes, R. A., &amp; Holtslag, A. A. M. (1998). A remote sensing surface energy balance algorithm for land (SEBAL): Part 1. Formulation. <em>Journal of Hydrology</em>, 212–213, 198–212.</p>
<p>Glenn, E. P., Huete, A. R., Nagler, P. L., &amp; Nelson, S. G. (2008). Relationship between remotely-sensed vegetation indices, canopy attributes and plant physiological processes: What vegetation indices can and cannot tell us about the landscape. <em>Sensors</em>, 8(4), 2136–2160.</p>
<p>Senay, G. B., Bohms, S., Singh, R. K., Gowda, P. H., Velpuri, N. M., Alemu, H., &amp; Verdin, J. P. (2013). Operational evapotranspiration mapping using remote sensing and weather datasets: A new parameterization for the SSEB approach. <em>Journal of the American Water Resources Association</em>, 49(3), 577–591.</p>
<p>Stanghellini, C. (1987). <em>Transpiration of greenhouse crops: An aid to climate management</em>. Agricultural University Wageningen.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>